using System.Text;
using System.Text.Json;

namespace SimpleRagApi.Services;

public class GeminiService
{
    private readonly HttpClient _httpClient;
    private readonly string _apiKey;
    private readonly string _chatModel;
    private readonly string _embeddingModel;
    private const string BaseUrl = "https://generativelanguage.googleapis.com/v1beta/";

    public GeminiService(HttpClient httpClient, IConfiguration config)
    {
        _httpClient = httpClient;
        var section = config.GetSection("Gemini");
        _apiKey = section["ApiKey"] ?? throw new ArgumentNullException("Gemini:ApiKey");
        _chatModel = section["ChatModel"] ?? "gemini-1.5-flash";
        _embeddingModel = section["EmbeddingModel"] ?? "text-embedding-004";
    }

    public async Task<float[]> GetEmbeddingAsync(string text)
    {
        var url = $"{BaseUrl}models/{_embeddingModel}:embedContent?key={_apiKey}";
        
        var requestBody = new 
        { 
            model = $"models/{_embeddingModel}",
            content = new { parts = new[] { new { text = text } } }
        };
        
        var requestContent = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json");
        
        var response = await _httpClient.PostAsync(url, requestContent);
        if (!response.IsSuccessStatusCode)
        {
            var error = await response.Content.ReadAsStringAsync();
            throw new Exception($"Gemini Embedding API error: {response.StatusCode} - {error}");
        }

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        var embedding = doc.RootElement
            .GetProperty("embedding")
            .GetProperty("values")
            .EnumerateArray()
            .Select(x => x.GetSingle())
            .ToArray();

        return embedding;
    }

    public async Task<string> AskAsync(string question, string context)
    {
        var url = $"{BaseUrl}models/{_chatModel}:generateContent?key={_apiKey}";

        var systemPrompt = "You are a helpful assistant. Answer the user's question using ONLY the provided context. " +
                           "If the context is insufficient, explicitly say there is not enough information. " +
                           "Do not invent facts. Keep the answer concise and clear.";

        var requestBody = new
        {
            contents = new[]
            {
                new 
                { 
                    role = "user", 
                    parts = new[] { new { text = $"System Instructions: {systemPrompt}\n\nContext:\n{context}\n\nQuestion: {question}" } } 
                }
            },
            generationConfig = new { temperature = 0 }
        };

        var requestContent = new StringContent(JsonSerializer.Serialize(requestBody), Encoding.UTF8, "application/json");

        var response = await _httpClient.PostAsync(url, requestContent);
        if (!response.IsSuccessStatusCode)
        {
            var error = await response.Content.ReadAsStringAsync();
            throw new Exception($"Gemini Chat API error: {response.StatusCode} - {error}");
        }

        var json = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(json);
        
        if (!doc.RootElement.TryGetProperty("candidates", out var candidates) || candidates.GetArrayLength() == 0)
        {
            return "Error: No response generated by Gemini. This might be due to safety filters or an empty context.";
        }

        var firstCandidate = candidates[0];
        if (!firstCandidate.TryGetProperty("content", out var content) || 
            !content.TryGetProperty("parts", out var parts) || 
            parts.GetArrayLength() == 0)
        {
            return "Error: Response content is missing or blocked.";
        }

        return parts[0].GetProperty("text").GetString() ?? string.Empty;
    }
}
